### ISSUE TITLE
Harvester

### ISSUE THREAD

**Issue by norbul** [Chia-Network/chia-docker#10]
I can not start harvester using this docker and cant add required certs

**Comment by norbul** [comment]
On main node I got
```
21:52:39.616 harvester src.harvester.harvester : INFO     0 plots were eligible for farming 324c0a0b6d... Found 0 proofs. Time: 0.00069 s. Total 5 plots
21:52:39.617 harvester harvester_server        : INFO     -> farming_info to peer 127.0.0.1 3d4692a392f3fe187037291e8f09a626bca8f83ff7f10387b39d6cbbbb47a26f
21:52:39.617 farmer farmer_server              : INFO     <- farming_info from peer 4a9fda04a66244517db303fe692af143d5ed3dd85139aec198bd5f7d63fb835a 127.0.0.1
```

And on harvester after plots check i got
src.plotting.check_plots         : WARNING  There are 1 plots with a farmer or pool public key that is not on this machine. The farmer private key must be in the keychain in order to farm them, use 'chia keys' to transfer keys. The pool public keys must be in the config.yaml

**Comment by justinengland** [comment]
you need to do the by hand setup same as on the main node in the container. chia init -c <ca_source> i will update the documentation to reflect that actual setup process shortly.

**Comment by NicodemPL** [comment]
Harvester only - will not start properly, there is some error in code:

Followed all steps from official wiki - all goes well until I start chia harvester.
Got error and this comes live in logs (below).

LOGS:

2021-04-27T14:37:37.303 daemon chia.daemon.server : ERROR problem starting chia_harvester
Traceback (most recent call last):
File "/chia-blockchain/chia/daemon/server.py", line 610, in start_service
process, pid_path = launch_service(self.root_path, exe_command)
File "/chia-blockchain/chia/daemon/server.py", line 766, in launch_service
process = subprocess.Popen(
File "/usr/lib/python3.8/subprocess.py", line 854, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chia_harvester'

If I do this as Ubuntu install not docker or Windows install, not docker - all works OK.
Tried with this docker on 3 different machines - every time same error about filename error in subprocess.py code.

**Comment by dconz13** [comment]
I'm having the same issue. I created the container using
`docker run --name chia -d -v /zpool/chia-plots/:/plots/ -v /home/dillon/chia/:/tmp-chia/ ghcr.io/chia-network/chia:latest -e harvester="true" -e farmer_address="xxx.xxx.xxx.xxx" -e farmer_port="8447" -e keys=""`

Then I followed the steps here for creating a harvester only node:
https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines

I also added the mnemonic with `chia keys add`.

Do we need to create a chia_harvester directory / file?

**Comment by esticle** [comment]
Same issue for me with same error

**Comment by dconz13** [comment]
I tried going into the docker container with `docker exec -it chia /bin/bash` and then executing `. ./activate` to see if maybe it had something to do with the virtual environment but it didn't work. It's weird it works when the docker container initially launches but not when manually restarting the daemon. It looks like the docker entrypoint.sh file is running the same commands we are trying to run manually.

**Comment by n1ghtwish** [comment]
Getting the same error where it can't start the harvester in docker, although it seems to have no problems doing so as a full node and operating the harvester as part of the full node.

**Comment by Dredok** [comment]
I can't run the harvester-only mode either ... followed the same guide as other guys:
I did the init using the CA of main machine
I added the keys of the main machine via chia key adds
I can telnet my main machine 8447 port

but no cigar

**Comment by NicodemPL** [comment]
So my solution for this is kind of simple - dont start harvester only. In docker config - do not change anything to true. Let it start as full node, harvester, farmer etc.
Once it finishes - log into docker and stop all manually:
./chia stop all
then
./chia start harvester

and it magically starts harvester then only. Works well.
I know its really dirt solution but at least working and you dont end up with many full nodes in one network (what is definitely not a good idea!)

**Comment by n1ghtwish** [comment]
Even better on my end, there is a docker parameter on mine for Harvester, when set to True it seems to do it's Harvester stuff without issue. I couldn't ssh in and get it to run Harvester only, but as a docker parameter it seemed to be happy.

**Comment by esticle** [comment]
> Even better on my end, there is a docker parameter on mine for Harvester, when set to True it seems to do it's Harvester stuff without issue. I couldn't ssh in and get it to run Harvester only, but as a docker parameter it seemed to be happy.

Thanks for this - works well for me as well!

**Comment by dconz13** [comment]
> 
> 
> So my solution for this is kind of simple - dont start harvester only. In docker config - do not change anything to true. Let it start as full node, harvester, farmer etc.
> Once it finishes - log into docker and stop all manually:
> ./chia stop all
> then
> ./chia start harvester
> 
> and it magically starts harvester then only. Works well.
> I know its really dirt solution but at least working and you dont end up with many full nodes in one network (what is definitely not a good idea!)

I tried starting the docker without the environment variables like you said and then followed the multi harvester guide again (stop chia, init with keys, edit harvester config file) and still can't start chia in harvester mode. I get a different error now though. Now it says `chia_harvester: chia_harvester failed to start. Error: start failed`
