### ISSUE TITLE
Multi-Arch Images

### ISSUE THREAD

**Issue by CyborgBill** [Chia-Network/chia-docker#101]
Hello,

Could you please build multi architecture images?  Especially armv7 for raspberry pi 4.  I would like to farm chia with my pi that has Libreelec installed on it, so docker images are pretty much my only option.  I'm sure there are many others that would like to be able to pull armv7 images too.  Thank you so much!

-CyborgBob

**Comment by mengland17** [comment]
Hi @CyborgBill - hope this helps you out, we have arm64 for rasp pi 4 : 

https://hub.docker.com/layers/chianetwork/chia-docker/latest/images/sha256-9ad3a22b8eea16e3e90feefae615c0271e0c5c7485ac3399afb3f3e1c2e736a0?context=repo
