### ISSUE TITLE
Issue with Harvester

### ISSUE THREAD

**Issue by Geelhem** [Chia-Network/chia-docker#102]
I am getting this and I can't figure out what setting needs to be changed :

Running 1.2.3 full node and Docker form A Synology NAS

![](https://cdn.discordapp.com/attachments/852299030905225296/865971072058261534/unknown.png)

**Comment by Pakue95** [comment]
Are you running a remote Harvester? Because it is trying to connect to a localhost address.

**Comment by Geelhem** [comment]
Running farmer, node and harvester locally. Node syncs fine but harvester does not seem to lock onto the daemon upnp is off ( as there an additional gui node on network) seems the trouble is with the address within the container
