### ISSUE TITLE
Generate smaller container images

### ISSUE THREAD

**Issue by stonemelody** [Chia-Network/chia-docker#109]
Is there any chance of something like #88 being merged to reduce the container image size? I've found some people that have gotten quite good at packing their NAS full of plots and now need to free up a whole plot's worth of space to store the 600MB docker image. Using build stages to reduce the image size would be a huge help, reducing the final container down to something like 200MB or so

**Comment by cmmarslender** [comment]
Yeah, I plan to look at #88 once I get a few of the other PRs taken care of (to avoid everyone else having to do massive rebases)

**Comment by cmmarslender** [comment]
Closed by #130 130
