### ISSUE TITLE
installing chia-docker

### ISSUE THREAD

**Issue by codingtrip** [Chia-Network/chia-docker#114]
# docker pull chianetwork/chia-docker:1.2.7
1.2.7: Pulling from chianetwork/chia-docker
no matching manifest for linux/arm/v7 in the manifest list entries

please help

**Comment by cmmarslender** [comment]
armv7 is 32 bit. Chia requires a 64 bit CPU https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#minimum-specs
