### ISSUE TITLE
Not able to spin up chia docker container

### ISSUE THREAD

**Issue by debasish22** [Chia-Network/chia-docker#115]
Hi ,

I have followed the steps to set up chia container but its not able to connect to peers
<img width="960" alt="Chia-loccal" src="https://user-images.githubusercontent.com/30689502/135239108-5840f695-1102-4a9e-af2c-ba96a0148b26.PNG">

**Comment by cmmarslender** [comment]
It looks like it was syncing and maybe just be hitting errors every now and then with some peers.. Is it still running? Can you see if it has made any more progress with syncing? If you were following the readme and have a container named chia, you can check on the status of syncing and peers with `docker exec chia chia show -sc`

**Comment by debasish22** [comment]
> docker exec chia chia show -sc
Yes @cmmarslender its syncing . but i am not able to find any data under path/to/plots. its empty. Can you please help where the data is getting pushed.

Below is the compose file i have :
version: "3.6"
services:
  chia:
    container_name: chia
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:latest
    ports:
      - 8444:8444
    volumes:
      - /mnt/c/Users/XXX/node-chia/path/to/plots:/plots


<img width="960" alt="Chia-loccal-syncing" src="https://user-images.githubusercontent.com/30689502/135383193-a269f405-58eb-4adc-aa84-aab6bd774c8e.PNG">
