### ISSUE TITLE
Slow syncing

### ISSUE THREAD

**Issue by bertybassett** [Chia-Network/chia-docker#12]
Got this installed on a Synology DS1821+ AMD AMD Ryzen™ Quad-core 2.2 GHz, 12 Gb of ram however the syncing to main net is painfully slow.  So far in 4 days I have gotten to 40000 is this normal.

Got me wondering if syncing is this slow will the container be fast enough to work as the farmer? How does one test that?

**Comment by justinengland** [comment]
syncing will take a while depending on your setup. it is recommended to copy over a db from a node that is fully synced. to speed up syncing on slower nodes. once fully synced it should be fine to farm/harvest.

**Comment by bertybassett** [comment]
But why so slow on such a descent spec’ed host?

**Comment by bertybassett** [comment]
for example running 

docker exec -it chia venv/bin/chia show -c -s

hangs for 45 seconds minutes before showing any results

**Comment by bertybassett** [comment]
docker exec -it chia venv/bin/chia wallet show
Exception from 'wallet' 'no active connection'

**Comment by justinengland** [comment]
you have no active wallet connections. your not synced so your wallet is not up and responding is my guess. 

Without knowing more about your setup, I can't really give and advise. If your running docker on windows, that is likely the source of your problems. Docker on mac performs even more poorly for file system based operations like this.

**Comment by justinengland** [comment]
I recommend joining keybase and reaching out to the support channel there for further assistance. closing this issue as github issues are not meant for tracking technical support requests not directly related to project features.
