### ISSUE TITLE
Log to file disabled by default

### ISSUE THREAD

**Issue by Gnomuz** [Chia-Network/chia-docker#123]
The recent commit 9f848dcd8994578ad7329aecb754d7b7822b684e had two changes :
- disable upnp by default, which does make sense in most cases, but may have raised issues for those running a full node and didn't pay attention to this new feature
- disable log to file by default, unless the variable `log_to_file` is set to `true`
I just helped a few pool mates to recover the logging to file, as they upgraded to 1.2.11 without watching the arguable implementation of this new feature.
As it is written now, if you launch the container without the variable explicitly set to `true`, it changes `log_stdout` to `true` in config.yaml, right.
The problem is if you relaunch the container with the variable set to `true`, it does nothing : 
`if [[ ${log_to_file} != 'true' ]]; then`
`  sed -i 's/log_stdout: false/log_stdout: true/g' "$CHIA_ROOT/config/config.yaml"`
`fi`
So to recover the logging to file you have to : 
- stop the container
- edit manually the config.yaml in the persistent storage to revert the unwanted change and set `log_stdout: false`
- relaunch the container with the variable `log_to_file` set to `true`
I can understand the author of the PR, who obviously doesn't care about logging to file, and that's his decision, wrote it this way.
I hardly understand how the PR could be approved as is without any analysis of the impacts, or - why not- an `else` clause to revert the changes in config.yaml in case the variable is reverted from default `false` to `true`...
Please pay attention to this docker, we are numerous running at least harvester-only nodes with it, and having to analyze each commit to prevent the unwanted consequences shouldn't be the standard imo.

**Comment by cmmarslender** [comment]
I have an open PR to set those to the old default values by default, to retain back-compat (aside from the couple days in here when it was reversed). Sorry for the confusion and change in default behavior, was a mixup while reviewing the defaults in the PR

**Comment by Gnomuz** [comment]
Thanks for the prompt reaction, that's obviously the right way to preserve previous defaults and offer new settings.
Well, I go back to my pool discord to support those who got trapped and are not docker experts 🥲

**Comment by cmmarslender** [comment]
PR is merged - should be building now
