### ISSUE TITLE
VDF-Client build interest?

### ISSUE THREAD

**Issue by Scribbd** [Chia-Network/chia-docker#131]
Since #130 got merged it is easier to include a VDF-build and not inflate the container image by too much. 

I already did some work to make the VDF client build in the container: https://github.com/Scribbd/chia-docker-slim/tree/bluebox

This adds about 4MB to the total payload and it would allow users with a Windows PCs (like mine) with spare calculation power to run VDF-clients in Docker.

There are some issues:
- Upstream `install-timelord.sh` assumes all Debian based systems are Ubuntu and will install snap as Debian-Bullseye is not >20.04
- With snap the script tries to install `cmake`
- Snap will not run inside a normal (unprivileged) container
- vdf-client build fails silently

I want to gauge interested in this option. I will continue working on it in my fork. However, to have it be a PR I estimate the following has to change:
- Upstream `install-timelord.sh` needs an update to account for non-ubuntu debian. (I could pick this up as well if there is interest)
- Something like #128 has to be merged in as another set of Dockerfile `ENV`s and `if`s in the `docker-start.sh` script will probably create chaos.

Let me know.

**Comment by cmmarslender** [comment]
I would love to see support for this in a container. Does your fork of this actually work now to where I could test the container in a few environments to see if it works, or is more work required?

I also like the change proposed in #128 just need that PR updated so there aren't any conflicts so I can run the CI and do a bit of testing.

**Comment by Scribbd** [comment]
> Does your fork of this actually work now to where I could test the container in a few environments to see if it works, or is more work required?

It builds. And `vdf_bench` runs. I haven't thoroughly tested it yet myself with a propper connection to a node.

Before I started testing I started focusing on #130 . I will look into it.

**Comment by xchdata1** [comment]
Being able to run timelord-launcher-only was part of the reason for #128 :) So yes, we'd definitely be interested in that too. Currently, we are running custom Docker images for pure bluebox vdf_client workers.

One issue with building vdf_client at Docker build-time is that more often than not, you want vdf_client built for the actual target CPU it will be running on. If, for example, you build on a non-AVX512 host but then run the container on a AVX512 machine, you'll be missing out on AVX512-specific performance optimisations. The other way round, it's even worse, of course. A vdf_client built on a AVX512 CPU won't run/will crash on a non-AVX512 CPU.

Thus, what we do for our custom containers is to allow vdf_client building either at container build-time or at container run-time.  Then you can use build-time install-timelord.sh for when you want to pre-build for well-known target hosts while instructing unknown targets to run their workers with run-time install-timelord.sh. I'm not sure if it's worth pre-building images with a vdf_client built for a "lowest common denominator" CPU; I think for public use of pre-built images, you want to build vdf_client on the actual target CPU, thus, at container-runtime.

If there's interest in this two-pronged buildtime/runtime vdf_client build approach, I should be able to quickly port it from our custom image to instead run on top of chia-docker's main branch.

**Comment by Scribbd** [comment]
@xchdata1 You have clearly already done more research into this. I haven't even thought about the implications of different instruction sets beyond the ARM64, ARMv7, AMD64 triad and not even though about their extension. Are there more extensions that have specific optimizations? And are these optimizations crucial if you want to run a bluebox? Which is my intention. 

For me it was more of providing an easy way for people to contribute with the compacting progress. To have them be able to just get an image and run that. By it's nature that doesn't have to be the fasted most optimized process. Or that is what I think. I could be wrong here.

With automation we could easily provide tag based images.  
Or if that is too much of a hassle because it is not just AVX512 but the whole slew of instruction extensions that needs to be counted for. Or that it isn't easily done with something like `buildx`. We could provide a `docker-compose.yaml` file that builds an image locally and we could instruct users to run that instead? Reducing the steps to `git clone` and `docker-compose up`.

**Comment by Scribbd** [comment]
@xchdata1 I am interested in seeing it. What is your opinion on what I proposed? (docker-compose with build step for cpu optimized images build on the machine. But a general most-common-denominator image for general use.)
