### ISSUE TITLE
Ability to disable wallet using environment variable

### ISSUE THREAD

**Issue by caeci11ius** [Chia-Network/chia-docker#133]
Would be nice to have a mechanism to disable the wallet while otherwise running the full node. I'm trying to save some memory usage.

**Comment by cmmarslender** [comment]
This is actually supported now with the merge of https://github.com/Chia-Network/chia-docker/pull/128

If you want to just run a full node, set the `service` env variable to `node` (it defaults to "farmer", which runs node, farmer, harvester, and wallet I believe). You can see what combinations of services are available with `chia start -h`

**Comment by cmmarslender** [comment]
If you're farming, and just don't want the wallet, but want all the other services that farmer usually runs, try setting `service` to `farmer-no-wallet`

**Comment by caeci11ius** [comment]
Ah lovely - the readme only mentions farmer-only...it's good to know the other modes are supported as well :-).
