### ISSUE TITLE
Four instances of chia_full_node running

### ISSUE THREAD

**Issue by caeci11ius** [Chia-Network/chia-docker#134]
Is it strictly necessary to have four instances of chia_full_node running? Collectively, they consume quite a bit of memory (admittedly, this is a pretty old machine - but I'd have thought requiring >4GB of RAM to run the fundamentals is perhaps a bit high...). Is there a way to reduce this to two, or even one instance? Haven't been able to find anything in the config file, environment variables or elsewhere...

Top output:

```
%CPU %MEM COMMAND
5.3  25.6 chia_full_node
0.0  24.4 chia_full_node
0.0  20.3 chia_wallet
0.0  20.2 chia_full_node
0.0  19.6 chia_full_node
0.0   1.0 chia_farmer
0.0   0.9 chia_harvester
```

**Comment by cmmarslender** [comment]
This isn't really an issue with `chia-docker` specifically, the same behavior can be seen installing chia-blockchain on linux outside of docker. I believe the number of processes you'll see depends on how many CPU cores you have available to help with sync or something, but not entirely sure. I'd suggest checking on the main chia-blockchain repo for any discussions or issues about this
