### ISSUE TITLE
Implement Healthcheck

### ISSUE THREAD

**Issue by Noki** [Chia-Network/chia-docker#136]
The node stopps functioning from time to time. Commands like `chia wallet show` or `chia show -s` fail in this case. It would be helpful to implement a healthcheck (https://docs.docker.com/engine/reference/builder/#healthcheck) so the container could be automatically restarted in this case.

**Comment by Starttoaster** [comment]
Added in https://github.com/Chia-Network/chia-docker/pull/137
Thanks for the suggestion!

**Comment by Gnomuz** [comment]
I do understand the interest of a healthcheck, unluckily the proposed implementation doesn't make sense when using this image to run a "harvester-only" container connected to a main farmer (see https://github.com/Chia-Network/chia-docker/issues/138)
I hardly understand how this PR was merged into the official image without checking it was applicable to both documented use cases (full node+farmer **_or_** remote harvester).
