### ISSUE TITLE
New Healthcheck irrelevant when running a harvester-only container ?

### ISSUE THREAD

**Issue by Gnomuz** [Chia-Network/chia-docker#138]
The latest PR (https://github.com/Chia-Network/chia-docker/pull/137) introduces a healthcheck which tries to connect to the full node RPC port 8555 (get_network_info).

I understand how this can be relevant when running the container as a full node and farmer, but I run a remote harvester connected to a full node and farmer instance located on another machine. As expected, this is done using the `service` variable set to `harvester` so that the start command is `chia start harvester`. This has been working fine for months now.
In that case, there's no full node at all, and the healthcheck will of course systematically fail due to the absence of a full_node process listening on port 8555.

I've updated a testnet harvester-only container recently. After the initial start period of 30 minutes and the default 3 retries every minute, the container is now showing as `unhealthy` which is totally misleading as this harvester is still communicating properly with the main farmer.

Through the `service` variable, this official image can run in two modes. Thanks in advance for assessing properly the consequences of PRs on both use cases, not only one of them. In my pool, the most common use case for this image is a remote harvester running on various NAS OSes, and I don't think we are an exception.

**Comment by Gnomuz** [comment]
PS : I know it can be run with `--no-healthcheck` as described in the readme, which is what I did. But please be aware not all "farmers" are experts with Docker and extra parameters, for instance those with Synology or QNAP NASes who run containers through an interface which has a limited set of options.

**Comment by cmmarslender** [comment]
This has been reverted for now - we'll investigate a healthcheck that can account for any combination of services running (or not) before merging back again in the future

**Comment by cmmarslender** [comment]
Hi @Gnomuz,

There is a new PR open that should address health checks for various was this container can be run. If you'd like to take a look, its https://github.com/Chia-Network/chia-docker/pull/148

**Comment by Starttoaster** [comment]
The referenced PR has been merged. @Gnomuz when you get a chance, could you please confirm if this is no longer an issue with the new healthcheck?

**Comment by Gnomuz** [comment]
Done, the new healthcheck is just fine here when running the container as a remote harvester-only.
Thanks for the good job !
