### ISSUE TITLE
Add curl to the image

### ISSUE THREAD

**Issue by CanaryInTheEtherMine** [Chia-Network/chia-docker#141]
Can we please have curl installed onto the official image so we can interact with the RPC API with exec commands from the Docker host.

I understand that a custom python requests script could be built and utilized, but it would be convenient to have the ability to test the RPC API of a pulled base image from inception without the need to customize the image.

**Comment by cmmarslender** [comment]
Yep, curl sounds completely reasonable. We added it recently in a healthcheck PR but that cause other issues so it was reverted. If you want to make a PR that just adds curl, I can get that merged. (Here's a relevant file that ended up reverted https://github.com/Chia-Network/chia-docker/blob/740578c142733f1aec9f8db3cecb8fdfb401dcec/Dockerfile#L38)

**Comment by CanaryInTheEtherMine** [comment]
Created pull request #142  for this.
