### ISSUE TITLE
How to specify  temporary directories?

### ISSUE THREAD

**Issue by soulmachine** [Chia-Network/chia-docker#15]
The `plots_dir` environment variable specify the final destination folder where you would like the plot to be stored, and usually it's recommended to  use a large slow hard drive. Am I understanding this `plots_dir` correctly?

This docker image has `plots_dir` environment variable for final directory, but doesn't have an environment variable to specify temporary directories, usually temporary directories are on fast SSDs.

**Comment by mikegreen** [comment]
I'm not sure you can specific a default temp and secondary temp env var, but what I did is mount both /plots/ and /plots_temp/:
-v /mnt/mycloud/plots/:/plots
-v /mnt/fast_drive/plots_temp:/plots_temp

Then to create a plot:
`docker exec -it chia-farmin-1 venv/bin/chia plots create -k 32 -b 4000 -t /plots_temp/ -2 /plots_temp/ -d /plots/`

Don't ask me why I map -2 (the 2nd temp location) to the same. When I did not map -2, I saw my container's volume start eating alot of space (40gb?) so I assume there is some logic/bug that it didn't use the -t /plots_temp/ for everything 🤷🏼

**Comment by soulmachine** [comment]
Got it, thanks!
