### ISSUE TITLE
custom command

### ISSUE THREAD

**Issue by AniBug** [Chia-Network/chia-docker#153]
I would like to get a custom command at startup (f.e. given in ENV-var), which existence is testet and then executed at start (f.e. in the entrypoint.sh) to do some customization:
install missing linux-commands
running custom health check or alert commands
install the preferred dashboard client (f.e. famr client)

I could define it in env: customcommand="/root/.custom/custom.sh" and mount a volume to /root/.custom. This will survive a container-update to a new version via watchtower.

**Comment by cmmarslender** [comment]
To me, that seems like a good use-case to just extend the image, using this image as the FROM, that way you aren't pulling all that in at run time.

**Comment by AniBug** [comment]
I just looked how machinaris pulls in the farmr client. They are using their own entrypoint.sh, where a whole bunch of stuff is installed. I am not expiereced in dockerfiles and like to get automated updates. Do I get the updates when I reference the FROM (latest)?

**Comment by cmmarslender** [comment]
Our latest tag is rebuilt for each stable release of chia, you just need to make sure to pull the latest version of the "latest" tag

**Comment by Starttoaster** [comment]
You can run custom healthchecks natively with docker. Docker has documentation for overriding the healthcheck instruction with your own.

Regarding installing additional packages, I agree with @cmmarslender that in general this seems like a crossroads where the better road to take would be to manage your own extension of this image.

**Comment by AniBug** [comment]
As my demand does not match the docker design ideas and the are other ways to implement this, I close this issue.
