### ISSUE TITLE
New Chia version required

### ISSUE THREAD

**Issue by NijaWarrior1** [Chia-Network/chia-docker#165]
I'm sure this is the wrong place, but I didn't found any better one: pls see official Chia announcement here https://www.chia.net/2022/03/04/divided-we-fork.en.html#farmers ... so we likely need a docker running 1.3 or higher... Thanks!

**Comment by cmmarslender** [comment]
There are docker images for each release that are created automatically. You can either use a version specific tag or `latest` to get the most recent released version (latest is currently 1.4.0). See https://hub.docker.com/r/chianetwork/chia-docker/tags

If you are already running `latest` and its still an old version, make sure to pull the new tag - `docker pull chianetwork/chia-docker:latest` and then run again
