### ISSUE TITLE
Persist blockchain sync

### ISSUE THREAD

**Issue by neoKushan** [Chia-Network/chia-docker#17]
I'm sure the answer to this is obvious, but with the current documentation I cannot find a straightforward answer.

When I start the container, naturally it begins syncing with the mainnet. But if I restart the container, the sync starts from the beginning.

The closest I can find is [this issue](https://github.com/Chia-Network/chia-docker/issues/12) where the advice is to copy the db from an already synced node - which I could do, but there's no information on how to do this?

I assume there's a volume I could mount to persist this database (And to copy an existing db into), but I can't find info on where this would be.

**Comment by justinengland** [comment]
you can either mount a local db volume to ~/.chia/mainnet/db/ 

or copy in a db from the host into the running contaner into that location.
