### ISSUE TITLE
When upgrading from version 1.5.0 to a newer version, a "Node healthcheck failed" error appears

### ISSUE THREAD

**Issue by figaro001** [Chia-Network/chia-docker#180]
Hi,

I stop the container, delete the container and when I start a new container I change the source from ghcr.io/chia-network/chia:1.5.0 to ghcr.io/chia-network/chia:latest or ghcr.io/chia-network/chia:1.5.1.

Then I look at the log:

2022-12-22T21:57:08.563 daemon chia.daemon.server         : INFO     chia-blockchain version: 1.6.1
2022-12-22T21:57:08.615 daemon chia.daemon.server         : INFO     Starting Daemon Server
2022-12-22T21:57:11.132 daemon chia.daemon.server         : INFO     ConnectionClosed. Closing websocket with Unknown
2022-12-22T21:58:00.154 Node healthcheck failed

Then only the lines appear:
Node healthcheck failed

I stop and delete the container, install the source ghcr.io/chia-network/chia:1.5.0 or another older container version and the container works again.

All actions are done on the same server. What can be the problem?

best regards,

Alex

**Comment by Starttoaster** [comment]
Hey Alex, do you happen to have any more details related to your configuration? I started a bunch of containers using the `1.5.0`, `1.5.1`, `1.6.0`, and `latest` tags, and I did notice some similar logs with the `1.5.1` image, which appears to be an issue with the websocket connection getting reset. Eventually, even `1.5.1` did start correctly for me, the node process is finding new blocks (seen with `chia show -s` ran in the container) and the docker healthcheck is passing. I didn't run a stopwatch until it started successfully, but I'd estimate less 3 minutes.

Could you maybe try using the `1.6.0` or `1.6.1` tags and see if either of those newer versions solve the issue you're encountering too?

**Comment by Starttoaster** [comment]
Hey @figaro001, since we haven't heard back from you in about 5 months, I'm going to assume this was resolved from your end. Please feel free to open up a new Issue if you still have issues on a recent version of the Chia docker image.
