### ISSUE TITLE
yq_x86 is used on arm image

### ISSUE THREAD

**Issue by grerrg** [Chia-Network/chia-docker#197]
When starting the newest version on arm, this comes up:

```shell
chia  | /usr/local/bin/docker-entrypoint.sh: line 84: /usr/bin/yq: cannot execute binary file: Exec format error
```

Suggestion:
1. Roll back #193 
2. Extend Dockerfile to to distinguish between Archs when installing yq
3. Use nixos as base image instead of ubuntu.

**Comment by Starttoaster** [comment]
Good callout and sorry for the incompatibility! This has now been rectified in the `1.7.0`, `1.7.1`, and `latest` tags of the image, and tested working on amd64 as well as arm64 machines.

**Comment by grerrg** [comment]
Awesome.

Totally like your solution.

Can verify for both `1.7.0`, `1.7.1`
