### ISSUE TITLE
docker harvester stops if one of recursive dirs has errored hdd which seems to be mounted properly.

### ISSUE THREAD

**Issue by chilio** [Chia-Network/chia-docker#202]
This problem refers to:
https://github.com/Chia-Network/chia-docker/issues/187#issuecomment-1500183777
which is still not resolved.
Here is what I've observed so far:
- in my case the first mounted dir (hdd drive) seems empty, but in fact it was errored drive which was still mounted, but showing no files
- as soon as I unmounted this faulty hdd and restarted docker with the same parameters everything went well and farmer could see all the plots from this harvester and other hdds mounted under.

Therefore I believe there is a not optimized check somewhere -> if the first dir containing plots fails then the whole container fails, but it should not fail since other dirs are having legitimate plots, as in my case.

**Comment by Starttoaster** [comment]
Hi @chilio ! Apologies, the old issue was closed due to inactivity. Since the context is there, let's re-open that issue and continue that conversation, if that's okay with you. Thanks!

**Comment by chilio** [comment]
@Starttoaster sure no problem, but the important part is now in this thread. Do you want me to copy this to the old one?
