### ISSUE TITLE
Compressed plot harvesting disabled by default

### ISSUE THREAD

**Issue by Fahrenheit2539** [Chia-Network/chia-docker#207]
Because parallel_decompressor_count is set to 0 by default, the container can't farm compressed plots.

While it is possible to supply custom config.yaml, that feels unintuitive.

Suggestion: allow passing parallel_decompressor_count via environment variable, and put some safe default (1?)

**Comment by Starttoaster** [comment]
Thanks for the Issue! We added a few environment variables just now to control various compressed plot settings, an updated image should be published from our build system shortly. You can see the short docs on them here https://github.com/Chia-Network/chia-docker#compressed-plots
