### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by emuhack** [Chia-Network/chia-docker#21]
in the gui editions of chia there are easy ways to specify the temp location and then the dump location for the plots. if we are running dockers as plotters only, then where do we set those options to crank out plots to the, lets say ubuntu farmer?

**Comment by justinengland** [comment]
that is going to be entirely implementation dependent. This docker container can run any version of the chia tools you need. full node, farmer, plotter. whatever. the specific configuration will be dependent on the end user. I recommend reading up on mounting host volumes into the docker container. that will get you a long way with your current question.
