### ISSUE TITLE
update readme 'chia show -c' has been renamed to 'chia peer -c'

### ISSUE THREAD

**Issue by grerrg** [Chia-Network/chia-docker#229]
Got this deprecation info. 
```bash
$ chia show -s -c
'chia show -c' has been renamed to 'chia peer -c'
[...]
```

Section #is-it-working in readme suggests running `docker exec -it chia venv/bin/chia show -s -c`.
The `-c` parameter triggers this warning.

I've updated the documentation and showed example outputs so it's easier to understand what the command should output when troubleshooting.

**Comment by Starttoaster** [comment]
Thank you for keeping the documentation up to date!
