### ISSUE TITLE
I started the container using the following parameters, but when connecting to the farmer, the certificate reported an error

### ISSUE THREAD

**Issue by JustAlias** [Chia-Network/chia-docker#235]
docker run -d --restart=unless-stopped -e TZ="Asia/HongKong" -e service="harvester" -e farmer_address="192.168.0.100" -e farmer_port="18447" -v ~/.chia:/root/.chia -v ~/.chia_keys:/root/.chia_keys  -v /home/share:/home/share/  --name="harvester" harvester:2.1.4

2024-02-26T13:13:29.647 harvester harvester               : INFO     Failed to connect to PeerInfo(_ip=IPv4Address('192.168.0.100'), _port=18447)
2024-02-26T13:13:32.650 harvester harvester_server        : DEBUG    Connecting: wss://192.168.0.100:18447/ws, Peer info: PeerInfo(_ip=IPv4Address('192.168.0.100'), _port=18447)
2024-02-26T13:13:32.664 harvester harvester_server        : INFO     Cannot connect to host 192.168.0.100:18447ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1007)')]

**Comment by JustAlias** [comment]
I have no problem starting on the host machine

**Comment by cmmarslender** [comment]
To have a remote harvester, it also needs to have certs signed by the same CA as the farmer.
You'll need to pass the CA to the container and set an env var that has its directory
`docker run ... -v ~/chia-ca:/chia-ca -e ca=/chia-ca ...`
The ca directory from the farmer (`CHIA_ROOT/config/ssl/ca`) needs to be in `~/chia-ca` in this example

**Comment by JustAlias** [comment]
> To have a remote harvester, it also needs to have certs signed by the same CA as the farmer. You'll need to pass the CA to the container and set an env var that has its directory `docker run ... -v ~/chia-ca:/chia-ca -e ca=/chia-ca ...` The ca directory from the farmer (`CHIA_ROOT/config/ssl/ca`) needs to be in `~/chia-ca` in this example


Thank you for reminding me that I made a mistake. I mistakenly assigned      ca=/root/. chia       which should be ca=/root/. chia/mainnet/ssl/ca         haha!


Is it necessary for me to use         "docker exec harvester venv/bin/chia plots add - d"          to add the plot directory for a new question to take effect, but the container must be restarted?

**Comment by cmmarslender** [comment]
You can set an env var for the plots dir as well `plots_dir`
`-e plots_dir="/path/to/plots"`

you can also set recursive plot scan to true if there are subfolders of plots in there
`-e recursive_plot_scan=true`

**Comment by JustAlias** [comment]
thank you  very much!

**Comment by cmmarslender** [comment]
Some of this is mentioned in the readme, but was looking at the `ca` param might not actually be mentioned there. If you want to take a stab at improving any of that in a pull request to make this information easier to find, feel free :)

**Comment by JustAlias** [comment]
> Some of this is mentioned in the readme, but was looking at the `ca` param might not actually be mentioned there. If you want to take a stab at improving any of that in a pull request to make this information easier to find, feel free :)

okk
