### ISSUE TITLE
When I put the container up to run on another offline machine it's always added /plots my plots_dir doesn't include it

### ISSUE THREAD

**Issue by JustAlias** [Chia-Network/chia-docker#241]
When I put the container up to run on another offline machine it's always added /plots my plots_dir doesn't include it

**Comment by Starttoaster** [comment]
Just to make sure I understand the issue you're describing here correctly:

You're running the container on machines (not sure if the machine being "offline" is a key detail here?) and no matter what you do it sets `/plots` from your `plots_dir` variable as a plot directory, though you haven't specified it? 

Can you give us more details about your docker run command or docker-compose file? Do you set `plots_dir` to anything else in there?

**Comment by JustAlias** [comment]
docker run --net=host -d --restart=unless-stopped -e service=harvester -e farmer_address=192.168.0.100 -e farmer_port=18777  -e ca="/chia-blockchain/ca/chiaca100/"  -v "/mnt/data/":"/mnt/data/":rslave -e plots_dir="/mnt/data/share/md1lv1:/mnt/data/md1lv2:/mnt/data/md1lv3:/mnt/data/md1lv4" -e log_level=INFO -e recursive_plot_scan=false -e healthcheck=false --name=harvester harvester:2.2.1

**Comment by JustAlias** [comment]
Above is my docker run command        
I'll use docker exec harvester chia plots show to get it when it's running

/plots
/mnt/data/share/md1lv1
/mnt/data/share/md1lv2
/mnt/data/share/md1lv3
/mnt/data/share/md1lv4

**Comment by JustAlias** [comment]
I may know why, there is an "ENV plots_dir=/plots" it will be added to my docker run "plots_dir" together
