### ISSUE TITLE
Container is dev-release

### ISSUE THREAD

**Issue by rundqvist** [Chia-Network/chia-docker#25]
Just re-created my container and it seems it is running the dev-release.

Command `docker exec -it chia venv/bin/chia version` returns: 1.1.3.dev0

I have tried the official way to fix this:
`# If you get RELEASE.dev0 then delete the package-lock.json in chia-blockchain-gui and install.sh again`
but there is no `package-lock.json` file in chia-blockchain-gui.

Don't know if this is a problem (other than potential bugs, since it is the dev-branch).

**Comment by justinengland** [comment]
this is just a github artifact. you are on the proper version of the software.
