### ISSUE TITLE
bladebit and other "included in 2.0" plotters are not included in the docker image

### ISSUE THREAD

**Issue by skandragon** [Chia-Network/chia-docker#263]

**Comment by Starttoaster** [comment]
I transferred this Issue over. Currently chia-docker doesn't have the plotters installed on purpose. Though we have considered adding it as an optional component that can be installed on container startup with an environment variable. We don't really plan on adding support for scripting the plotters actually creating plots. Though we have also considered allowing for something like an environment variable that defines the path to a script that you could make yourself and mount inside the container.

**Comment by Starttoaster** [comment]
The kubernetes operator has no plans at this time to support generating plots within it. It is the intention of the operator to be a good place for farms to operate, but generating the plots for a farm would be a detail left to the end user, likely on a baremetal installation of chia. As is the case for the majority of people plotting today.
