### ISSUE TITLE
Host I/O rate.

### ISSUE THREAD

**Issue by pecet66** [Chia-Network/chia-docker#27]
Hello

I have run docker stats command
`docker stats`
And saw that it reports **8.71TB** of writes to host. Yet I plotted only one k32 on this container, and it' in harvester mode. From chia documentation, it is supposed to write approx 1.7TB for each plot. I wonder why my stats are that high and what could be the case. Can be there something wrong with my host setup?
Can somebody check how much your image reports for one plot on block i/o ?
`
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O         PIDS
`
`
66e51a4b1b32   chia-3    0.00%     389.5MiB / 15.53GiB   2.45%     406kB / 292kB   8.71TB / 6.98MB   0
`

**Comment by justinengland** [comment]
github issues are not for tech support. please check out keybase for support.
