### ISSUE TITLE
Reasoning behind expose vs publishing port?

### ISSUE THREAD

**Issue by mikegreen** [Chia-Network/chia-docker#29]
Is the container meant for actual usage or more testing? Asking because it currently exposes a port vs publish (which would allow it to be mapped as a participating node). 
I guess its easy enough to start it with `-p 8444:8444` if so?

**Comment by KipiKland** [comment]
That docker can run as a full node, in headless mode, and have a Linux or Win 10 GUI remotely connect to it through TCP55400.

Docker documentation:  Given that the container does not have its own IP-address when using host mode networking, port-mapping does not take effect, and the -p, --publish, -P, and --publish-all option are ignored, producing a warning instead:
WARNING: Published ports are discarded when using host network mode

As a consequence
- if port 8444 is not taken by another app on host, and host firewall allows it, it will be available for the container
- of course your router must forward such port to your host ip for other nodes to connect.
