### ISSUE TITLE
UI ?

### ISSUE THREAD

**Issue by vorburger** [Chia-Network/chia-docker#37]
Does this container include a working UI?

The `chia/mainnet/config/config.yaml` file generated by `chia init` has `ui: port: 8222`, but that port currently is not `EXPOSE`-d in the Dockerfile (only 8444 & 8555) - should it be?

**Comment by vorburger** [comment]
I've tried to `docker run -p 8222:8222 ...` but http://localhost:8222/index.html does not respond in a web browser.

**Comment by TheGreatBungholio** [comment]
Same problem here - anybody found a solution to this yet?

**Comment by Skaronator** [comment]
https://github.com/Chia-Network/chia-blockchain-gui/issues/266

**Comment by guydavis** [comment]
> Same problem here - anybody found a solution to this yet?

Yes, faced this too on Unraid.  So I created a derived Docker image, named [Machinaris](https://github.com/guydavis/machinaris), which includes a basic WebUI and integrates Plotman.  Hope this helps!

**Comment by justinengland** [comment]
no it does not include a working ui
