### ISSUE TITLE
Log to stdout instead of log/debug.log when running in container

### ISSUE THREAD

**Issue by vorburger** [Chia-Network/chia-docker#38]
The `chia/mainnet/config/config.yaml` file generated by `chia init` has `log_stdout: false` and `log_filename: log/debug.log`.

In an ideal world, [containers should log only to STDOUT](https://12factor.net/logs), not to files inside the container.

One can manually change the `config.yaml` (IFF it's maintained outside the container, as proposed in #36), but in an ideal world, perhaps this container should set it up to log only the STDOUT out of the box?

**Comment by davidbarratt** [comment]
I added a line to `tail` the log file for now in #77
