### ISSUE TITLE
Operation Not Permitted when moving to final destination that is na nfs share. 

### ISSUE THREAD

**Issue by BBBosp** [Chia-Network/chia-docker#40]
Using a privileged podman container with multiple bind mounts for temp directories and a nfs mount on the host used for plots directory. I have  full privileges to make delete and rename files on the nfs share, but the final step copying the *.plot.2.tmp file to the nfs share mounted at /plots says Operation Not Permitted trying again in 5 minutes.

**Comment by mengland17** [comment]
is this still an issue you are having?

**Comment by BBBosp** [comment]
> is this still an issue you are having?

Actually not sure, I moved to MadMax plotter instead of plotting with this container so It's become a non issue for me.
