### ISSUE TITLE
Two and more paths with plots

### ISSUE THREAD

**Issue by Vinticb** [Chia-Network/chia-docker#44]
Hello. I have 3 hdd with plots. How can i use more than one path with plots?

**Comment by Gnomuz** [comment]
Same as you, just create 2 other paths like /plots1 and /plots2, mapped to your hard drives 2 and 3, add them to the harvester from within the container with 'chia plots add -d /plots1' and 'chia plots add -d /plots2'. If, and I hope so for you, your config.yaml is in a persistent storage, the amendment will remain over restarts and rebuilds of the docker.
Just a workaround, but I hope it can help.
