### ISSUE TITLE
rebuild for 1.1.5

### ISSUE THREAD

**Issue by kaspar030** [Chia-Network/chia-docker#45]
Seems like the container is not automatically rebuilt when there's a new chia release.

Pulling now still gets 1.1.4.

**Comment by pperzyna** [comment]
@justinengland @thdxr @kemp @nirajpathak13

**Comment by kaspar030** [comment]
seems solved to me, I pulled 1.1.5 recently.

**Comment by kaspar030** [comment]
Thanks a bunch!
