### ISSUE TITLE
Run as non-root user

### ISSUE THREAD

**Issue by benv666** [Chia-Network/chia-docker#52]
Hi folks,

Is there a good reason the docker runs as the root user? (I don't see it at least)
I am aware of the user mapping option that docker provides (e.g. https://docs.docker.com/engine/security/userns-remap/) , but a lot of users won't bother.

Suggestion:
Create a chia user and group with their own homedir in the Dockerfile and run using that instead of root.

**Comment by caeci11ius** [comment]
Went to the trouble of setting up users to run this container as only to discover there was no easy way to do it. Took a look at the user mapping mentioned above but it all seemed a bit much for someone who has a fairly rudimentary knowledge of docker...

**Comment by justinengland** [comment]
not worth the effort. The user space inside the container doesn't really matter that much IMO.

**Comment by benv666** [comment]
I respectfully disagree, there is no good reason to run as root in this container.

Worse, it makes it easy for an attacker if they manage to break into the container to do whatever they want in there, but potentially also to break things for the host system.

See https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html or [many](https://amazicworld.com/get-the-evil-out-dont-run-containers-as-root/#:~:text=One%20reason%20to%20do%20so,being%20used%20inside%20the%20container.) [other](https://betterprogramming.pub/running-a-container-with-a-non-root-user-e35830d1f42a) [blogs](https://jfrog.com/knowledge-base/3-essential-steps-to-securing-your-docker-container-deployments/).

**Comment by adarobin** [comment]
@justinengland What about the poor machine that is hosting the container?
