### ISSUE TITLE
Can it be set not to automatically generate a key? 

### ISSUE THREAD

**Issue by jjasoncool** [Chia-Network/chia-docker#54]
Every time I use `docker start`, I can always see that a new key is generated. 
Can I turn off this function? 
Or where I can configure it ?

**Comment by Gnomuz** [comment]
You can use the "mnemonic" variable as a pointer to your mnemonic.txt file for the first run, to have your real keys imported in config.yaml. Of course delete the mnemonic.txt file after the first run, having it inside a container connected to the internet is not the best security practice ...
But leave the mnemonic variable pointing to the deleted file. When you will restart the container, you'll get a "file not found" error, but it won't generate new keys @ each restart, they will remain static in the config.yaml (provided the ~/.chia directory is mapped to a persistent storage, of course).
It's just a crappy workaround, but I hope it can help. This docker image is obviously not a priority for the development team ...

**Comment by BenneX** [comment]
As far as I understood if you pass -e keys=""
it also shouldn't recreate keys, but also won't have any

**Comment by horego** [comment]
Hey there. I made a fixed version of this repo. Including the time(zone) problem mentioned in https://github.com/Chia-Network/chia-docker/issues/28

You can also skip the generation/import of keys by setting keys variable to "none". Feel free to give it a try or build it on your own.

https://github.com/horego/chia-docker

**Comment by justinengland** [comment]
can you submit a pr with your none change for the key generation @horego ?
