### ISSUE TITLE
Community/dev branch

### ISSUE THREAD

**Issue by LCerebo** [Chia-Network/chia-docker#55]
I assume that right now the developers are laser-focused on pooling, unfortunately the chia-docker repo has plenty useful PRs ready to be approved, that are several days old. It will be nice to have a community/dev branch (and relative docker tag deployed) in which PR are merged after 2 or 3 community approvals.
2-3 seems a fair number but could be more.

**Comment by justinengland** [comment]
I will consider this suggestion. Not a bad idea. let me think it over for a bit.
