### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by ygcool** [Chia-Network/chia-docker#56]
![image](https://user-images.githubusercontent.com/16422689/118348790-333c5c80-b57f-11eb-8ea2-a3fcd0f67361.png)
![image](https://user-images.githubusercontent.com/16422689/118348804-46e7c300-b57f-11eb-97cd-495e1016abc3.png)

**Comment by ohld** [comment]
hey! I just had the same problem. What was your solution?
