### ISSUE TITLE
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address stderr 17:36:54

### ISSUE THREAD

**Issue by bertybassett** [Chia-Network/chia-docker#6]
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address | stderr
-- | --

what is wrong here?

**Comment by bertybassett** [comment]
use the same network as the dock host

**Comment by kevinkk525** [comment]
that's not really a solution to the problem imho

**Comment by kevinkk525** [comment]
So you can solve the issue by changing in config.yaml the variable "self_hostname:" from "localhost" to "0.0.0.0"
