### ISSUE TITLE
How to check log files

### ISSUE THREAD

**Issue by filzek** [Chia-Network/chia-docker#60]
I have sucessful install the docker and run it, but I cant find where the log files are located on docker

**Comment by PhilPhonic** [comment]
`/root/.chia/mainnet/log/debug.log`

The loglevel is set to INFO by default. If there is no logfile, there are no log messages "higher" than INFO (WARN, ERR, etc)

**Comment by sdbarrish** [comment]
> `/root/.chia/mainnet/log/debug.log`
> 
> The loglevel is set to INFO by default. If there is no logfile, there are no log messages "higher" than INFO (WARN, ERR, etc)

That doesn't show log info from the docker container harvester node. Only on the farm node where the farm node has plot directories pointed to it.

**Comment by PhilPhonic** [comment]
> 
> 
> > `/root/.chia/mainnet/log/debug.log`
> > The loglevel is set to INFO by default. If there is no logfile, there are no log messages "higher" than INFO (WARN, ERR, etc)
> 
> That doesn't show log info from the docker container harvester node. Only on the farm node where the farm node has plot directories pointed to it.

It does for me in harvester mode.. set the loglevel to INFO, restart the container, check again..
