### ISSUE TITLE
No new image available with approved pull requests

### ISSUE THREAD

**Issue by Gnomuz** [Chia-Network/chia-docker#61]
Thanks for approving some of the pending pull requests from the community (including my proposal to add tzdata).
Could you please build the image including them with the newly released 1.1.6 ? I always prefer using official images rather than forks by others or myself in terms of maintenance. So, for the moment I can't upgrade my full node to 1.1.6 as I run a harvester in the container pulled from the 11 days old 'latest' tag.
Thanks in advance

**Comment by Warmduscher** [comment]
Looks like the automated workflow is beeing blocked by the dreaded `tzdata` package. Blocking automated docker builds all over the world.

Someone already made a pr for this: https://github.com/Chia-Network/chia-docker/pull/62 hopefully this gets approved soon and will solve the issue

**Comment by VanQz** [comment]
Agreed. TZ is required as some people are having issues with the docker and local time not in sync. Any programs fetching time from the logs would be totally incorrect.

**Comment by zette** [comment]
tzdata is easily mitigated with mapping /etc/localtime into container: `-v /etc/localtime:/etc/localtime`

**Comment by VanQz** [comment]
> tzdata is easily mitigated with mapping /etc/localtime into container: `-v /etc/localtime:/etc/localtime`

Tried this didnt work

**Comment by justinengland** [comment]
new images have the staged changes from before the most recent release. next release of chia software will have the next batch of staged changes.
