### ISSUE TITLE
Will not keep sync Version 1.1.6

### ISSUE THREAD

**Issue by Yamanipanuchi** [Chia-Network/chia-docker#67]
Had issues syncing with 1.1.5, I beleive it was a known issue. Now that I have it upgraded to 1.1.6 which should have resolved the issue. It hasent.

Current Blockchain Status: Not Synced. Peak height: 315224
      Time: Fri May 21 2021 17:13:43 America                  Height:     315224

I have 4 different machines running chia in 3 different locations. All of them had this syncing issue. The three windows machines I have, now that there upgraded to 1.1.6 have no sync issues at all. But the docker still has this issue.

Port 8444 has been checked countless time to be open and ready. UPNP is shut off both in chia config and router. I've had external users connect to chia running in the docker and connection successful. I can confirm my windows connects to docker and docker connects to windows. I would assume it would sync of the local windows chia with no issues.

CPU usage on docker is at about 30-40%.

Sync is trying, But its almost like it cant sync fast enough to keep up with the growing blocks.

I am unsure what else to try?

**Comment by neoKushan** [comment]
Are you sure you've upgraded to 1.1.6? If you're using the container, it has not been updated.

Run `chia version` to see (note if it says `1.1.6-dev0` then this is NOT 1.1.6).

**Comment by Yamanipanuchi** [comment]
It is 1.1.6-dev0. Darn, I guess I was overly excited to see it start working again. Ill wait till the container is updated.
