### ISSUE TITLE
New version of chia

### ISSUE THREAD

**Issue by Luiso0o** [Chia-Network/chia-docker#70]
Now we have the version 1.1.6 Chia Blockchain 2021-05-20

¿How can I update to that version?

I have a problem with this version, it is always on syncing and don't works.

**Comment by hackers365** [comment]
same question

**Comment by hackers365** [comment]
`docker pull ghcr.io/chia-network/chia:latest
`


chia:latest image will update to 1.1.7 dev0

**Comment by Luiso0o** [comment]
do you know when?

**Comment by Jharmony** [comment]
will his version work on my Qnap arm/v7? When I try to pull from ghcr.io/chia-network/chia:latest I get an error.
