### ISSUE TITLE
ENTRYPOINT should be CMD

### ISSUE THREAD

**Issue by davidbarratt** [Chia-Network/chia-docker#76]
The image should allow me to run any arbitrary command without starting up Chia itself, but since it's an entry point I cannot use [docker run](https://docs.docker.com/engine/reference/commandline/run/) with a command
https://github.com/Chia-Network/chia-docker/blob/97a13dfdd785d0987709a76fdf9de4ac0cf42595/Dockerfile#L28

**Comment by skweee** [comment]
This is exactly what "--entrypoint" is for:
`docker run -it --entrypoint <your_command>`

Please don't change the default entrypoint.

**Comment by davidbarratt** [comment]
> An ENTRYPOINT allows you to configure a container that will run as an executable.

https://docs.docker.com/engine/reference/builder/#entrypoint

So is `chia` an executable or is it something that _runs_. If it's the latter (which is how it's currently set up), it should be `CMD`

**Comment by davidbarratt** [comment]
> The main purpose of a CMD is to provide defaults for an executing container. These defaults can include an executable, or they can omit the executable, in which case you must specify an ENTRYPOINT instruction as well.

https://docs.docker.com/engine/reference/builder/#cmd
