### ISSUE TITLE
Add variable to set Log Level

### ISSUE THREAD

**Issue by sparklyballs** [Chia-Network/chia-docker#82]
Would it be possible to add an environment variable to be able to set the log level for chia in the container, something along the lines of
`-e log="INFO"`

This would make it practically stateless for harvester only nodes and let us see the proofs etc ticking over, without having to stop the container, edit the config.yaml, and restart the container

**Comment by Artanicus** [comment]
This is a must. Since currently there is no other way to monitor for node health, increasing the log level & parsing the logs is the only option at the moment.

**Comment by Artanicus** [comment]
Still relevant.

**Comment by sparklyballs** [comment]
yes, still relevant

**Comment by TOoSmOotH** [comment]
https://github.com/Chia-Network/chia-docker/pull/99

There is a PR that is sitting there that has this in it.

**Comment by Artanicus** [comment]
Not stale.

**Comment by cmmarslender** [comment]
There is another PR that was going to add this, but seems like it was never completed. If someone is open to making a PR for just the log level, I'd accept that. It was already basically done here https://github.com/Chia-Network/chia-docker/pull/99/files just has other incomplete work that I can't merge
