### ISSUE TITLE
how to use a exsist status of current full node

### ISSUE THREAD

**Issue by JsBlueCat** [Chia-Network/chia-docker#95]
we know that the blockchian cache the current status in layerdb. and save it to wallet folder.

when using docker , is there any way to use exsist db file?  so that we need not to sync is again (which may consume lots of time).

is there -v can map the current file into docker?

**Comment by pbodq2** [comment]
Yes, you can map those DB folders by -v as well as the config.yaml and ca (ssl) folders, etc

Chia software basically includes two big files, the mainnet blockchain database file and the wallet blockchain database file. Up to 23-Jul-2021, both DB files cost over 10 GBytes. Everytime you upgrade your Chia version in Docker platform, the container cache and image will be destroyed and you have to re-download the DBs from peers over the world, very slowly. (If you don't backup those sqlite files)

![DSM](https://user-images.githubusercontent.com/25418300/126726073-46268a9f-fab7-4104-a049-c050e88300ca.png)

Imagine some people use WatchTower to auto update images and containers,  I suspect significant netspace drops in chiaexplorer.com statistics is the consequences when each new software version was released.

Developers should better provide convenient environment variables setting to these folder paths. That will be convenient to Docker users and we need not inspect into the paths anymore.

My feeling is that Docker platform is a lame to them, dev tag as production latest, lack of environment variables preset. Their focus is on GUI like Windows which consumes more electricity / hardware cost, unlike other mining projects such as Storj which is Docker oriented.

**Comment by mengland17** [comment]
Did the above response help or are you still having issues/questions?

**Comment by Mi-Q** [comment]
At least for me, watching this issue this helped a lot! Took me 5 days or so before to re-sync every time the docker war recreated on my QNAP
